name: Deploy to S3 on Tag

on:
  push:
    branches: 
      - 'test-workflow'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
      - '[0-9]+.[0-9]+.[0-9]+*'
      - 'v[0-9]+.[0-9]+.[0-9]+-(CR|Beta|milestone)[0-9]*'
      - '[0-9]+.[0-9]+.[0-9]+-(CR|Beta|milestone)[0-9]*'

permissions:
  id-token: write   # Required for requesting the JWT
  contents: read    # Required for actions/checkout

jobs:
  Golden-Image:
    runs-on: ubuntu-latest
    continue-on-error: false
    env:
      IS_TEST: ${{ github.ref == 'refs/heads/test-workflow' }}
      TAG_NAME: ${github.ref_name}
      REPO_NAME: ${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}
      S3_BASE_PATH: "s3://bootstrap-opinion-stg/playbooks"
      S3_PATH: "${S3_BASE_PATH}/${REPO_NAME}/${TAG_NAME}"
    
    steps:
      - name: Determine Tag
        if: ${{github.ref_type == "tag" || IS_TEST}}
        
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::992382682634:role/ansible-playbook-workflow-role
          aws-region: il-central-1

      - name: Install Packages
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli packer    

      - name: Delete existing files from S3
        if: env.TAG_NAME
        run: |
          aws s3 rm ${{ env.S3_PATH }}/ --recursive

      - name: Upload files to S3
        run: |
          aws s3 cp . ${{ env.S3_PATH }}/ --recursive --exclude ".*" --exclude ".*/**" --exclude "Vagrantfile*"

      - name: Install Packer Plugin for Amazon
        run: |
          packer init .

      - name: Execute Packer Build
        run: |
          packer build -var "tag=${TAG_NAME}" .
