name: Deploy to S3 on Tag

on:
  push:
    branches: 
      - 'test-workflow'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
      - '[0-9]+.[0-9]+.[0-9]+*'
      - 'v[0-9]+.[0-9]+.[0-9]+-(CR|Beta|milestone)[0-9]*'
      - '[0-9]+.[0-9]+.[0-9]+-(CR|Beta|milestone)[0-9]*'

permissions:
  id-token: write   # Required for requesting the JWT
  contents: read    # Required for actions/checkout

jobs:
  check-out-repository:
    runs-on: ubuntu-latest
    continue-on-error: false
    env:
      IS_TEST: ${{ github.ref == 'refs/heads/test-workflow' }}
      TAG_NAME: ${{ github.ref_name }}
      REPO_NAME: ${{ github.repository }}
      S3_BASE_PATH: "s3://bootstrap-opinion-stg/playbooks"
    
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: calling reusable workflow
        uses: ./.github/workflows/reusable-workflow.yml