name: Deploy to S3 on Tag

on:
  push:
    tags:
      - '*'  # Trigger on any tag

jobs:
  S3PackageUpload:
    runs-on: ubuntu-latest
    
    if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')
    
    steps:
      - name: Ensure this is a tagged commit on master
        run: |
          if [[ "${GITHUB_REF}" != refs/tags/* ]]; then
            echo "Not a tag. Exiting."
            exit 1
          fi
          
      - name: Git clone the repository
        uses: actions/checkout@v4
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::992382682634:role/ansible-playbook-workflow-role
          role-session-name: samplerolesession
          aws-region: il-central-1
          
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
      
      - name: Set Variables
        id: vars
        run: |
          TAG_NAME=${GITHUB_REF##*/}
          REPO_NAME=${GITHUB_REPOSITORY##*/}
          echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_ENV
          echo "REPO_NAME=${REPO_NAME}" >> $GITHUB_ENV
      
      - name: Delete existing files from S3
        run: |
          aws s3 rm s3://bootstrap-opinion-stg/playbooks/${REPO_NAME}/${TAG_NAME}/ --recursive
      
      - name: Copy to S3
        run: |
          aws s3 cp . s3://bootstrap-opinion-stg/playbooks/${REPO_NAME}/${TAG_NAME}/ --recursive --exclude ".*" --exclude ".*/**" --exclude "Vagrantfile*"