name: Deploy to S3 on Tag

on:
  push:
    tags:
      - 'v*'
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: configure-aws-credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: il-central-1
          
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
      
      - name: Set Variables
        id: vars
        run: |
          TAG_NAME=${GITHUB_REF##*/}
          REPO_NAME=${GITHUB_REPOSITORY##*/}
          echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_ENV
          echo "REPO_NAME=${REPO_NAME}" >> $GITHUB_ENV
      
      - name: Copy to S3
        run: |
          aws s3 cp . s3://bootstrap-opinion-stg/playbooks/${REPO_NAME}/${TAG_NAME}/ --recursive --exclude ".*" --exclude ".*/**"
